name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      run: |
        npm install
        npm run test
        echo ${GITHUB_REF}
      env:
        NODE_ENV: test
        CI: true
        DUST_API_KEY: 'XtvRvBVCs1VmlZD8KfgO5zLmYV73SGNrvw5HucyJL4ppQPfmCd7cYpnJ7zbQpQioZVrnUySbpC82lsfr8s5gng%3D%3D'
        FORECAST_TOKEN: '677351504163558e6b83764082c12e8d'
        FOOTBALL_KEY: '61b031ab5dmsh20359493ae08a90p19602djsnf5bf002e22d8'
        HOLIDAY_API_KEY: 'lBBRnvK6Ek%2BPnb tG3t1M7FJb13qDfUC8CqW2vcRF6s%2B0cBaeeUxpwOziJ7SzBnpmN6ZBQ5TPcisYZ%2BoM8gXy%2BA%3D%3D'
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: github ci # Optional.
        SLACK_CHANNEL: test # Optional.
        SLACK_OVERRIDE_MESSAGE: ${{ matrix.node-version }} build 및 test 완료 https://github.com/taehyeong224/slack-bot/commit/${{github.sha}}
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new commit has been pushed.'
  release:
    runs-on: ubuntu-16.04
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login
    - name: push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:push -a calm-fortress-1234 web
    - name: release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:release -a calm-fortress-1234 web
